import type { NextPage } from "next";
import Head from "next/head";
import Agenda from "../components/Agenda";
import HeroSection from "../components/HeroSection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MJ Designs - Elegant, Quality Graphic & UI/UX Designing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection />
        <Agenda />
      </main>
    </div>
  );
};

export default Home;
